### PR TITLE
Fix accordion for square prop

### LINKED ISSUE #221: Accordion "square" prop not getting applied
### Latest version

- [x] I have tested the latest version

### Steps to reproduce

Steps:
1.  For Accordion component try to apply prop "square" so that accordion doesnot have border radius.
2. "square" doesnot make the accordion remove the border radius
3. It is because borderRadius is hardcoded.

Image

### Current behavior

After applying square prop accordion doesnot appear square and border radius is seen.

### Expected behavior

After applying "square" prop accordion should appear square without having border radius.

### Context

_No response_

### PR DESCRIPTION
**Pull request by ramanjotSingh-HCL**
Fixed #221

### CODE REVIEW

File: src/Accordion/Accordion.tsx [hunk 1]
```diff
@@ -80,16 +80,6 @@ const StyledAccordion = styled(MuiAccordion)<AccordionPropsAll>((props) => {
...
-    '&:first-of-type': {
-      borderTopLeftRadius: '4px',
-      borderTopRightRadius: '4px',
-      borderBottomLeftRadius: '0px',
-      borderBottomRightRadius: '0px',
-    },
-    '&:last-of-type': {
-      borderBottomLeftRadius: '4px',
-      borderBottomRightRadius: '4px',
-    },
```
Comment (rubyannmatias) [inline src/Accordion/Accordion.tsx:92]: IF the change is for when prop square = true
e.g.
<Accordion square />

Should we not be able to control it from the Interactive example?

Can you add an interactive control for it in Accordion.stories.tsx? Thanks!

I think we only want the style changes you've made to apply when square=true
Maybe you can add it as a condition here? Thanks!

const StyledAccordion = styled(MuiAccordion)<AccordionPropsAll>((props)

---

Goal is to have square controllable from the right side panel, thanks 

Screenshot 2025-06-27 at 6 16 32 PM

**Review by rubyannmatias — CHANGES_REQUESTED** [review]

File: src/Accordion/Accordion.tsx [hunk 2]
```diff
@@ -80,16 +81,6 @@ const StyledAccordion = styled(MuiAccordion)<AccordionPropsAll>((props) => {
...
```
Comment (rubyannmatias) [inline src/Accordion/Accordion.tsx:92]: Hello @ramanjotSingh-HCL 
Thanks for adding the interactive example.

However, I still don't see any condition in the styles above, that the removal of border radius only happens when props.square === true? 

I think other teams are using the Accordion with square = false

Let me know if we need to set up a call to clarify this with designers or initial implementor of Accordion @PiyushKashyapHCL

**Review by rubyannmatias — CHANGES_REQUESTED** [review]

**Review by rubyannmatias — APPROVED** [review]
Got it, thanks for explaining @ramanjotSingh-HCL
